name: Deploy API to Heroku Prod

on:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"
      - ".github/workflows/api.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Build api
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          cd apps/api
          npm i --ignore-scripts
          npm run db:migrations:build
          npm run build
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git config http.postBuffer 524288000
          git add -f migrations-js
          git add -f dist
          git commit -m "Built latest;"
          cd ..
      - name: Add api remote origin
        run: git remote add heroku-prod https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/vml-image-tools-api.git
      - name: Deploy api to Heroku
        run: git push heroku-prod `git subtree split --prefix=apps/api main`:refs/heads/master --force
